apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-web
spec:
  selector:
    matchLabels:
      app: api-web
  replicas: 1
  template:
    metadata:
      labels:
        app: api-web
    spec:
      containers:
        - name: api
          image: index.docker.io/gadigamburg/finalproject:intapi_{{API_Version}}
          imagePullPolicy: Always
          command: [ "echo", "API SUCCESS" ]
          ports:
            - containerPort: 3000
          readinessProbe:
              httpGet:
                path: /
                port: 3000

        - name: web
          image: index.docker.io/gadigamburg/finalproject:intweb_{{WEB_Version}}
          imagePullPolicy: Always
          command: [ "echo", "WEB SUCCESS" ]
          ports:
            - containerPort: 5000

        - name: db
          image: index.docker.io/mongo
          imagePullPolicy: Always
          command: [ "echo", "DB SUCCESS" ]
          ports:
            - containerPort: 27017

