apiVersion: v1
kind: Service
metadata:
  name: api-web
  labels:
    app: api-web
spec:
  type: NodePort
  selector:
    app: api-web
  ports:
  - protocol: TCP
    name: http
    port: 3000
    targetPort: 3000
    port: 5000
    targetPort: 5000